local values = {}

-- boat
values.BOAT_MAX_SPEED_DEFAULT = 50
values.BOAT_MAX_BACKWARD_SPEED_DEFAULT = values.BOAT_MAX_SPEED_DEFAULT / 2
values.BOAT_ACCELERATION_DEFAULT = values.BOAT_MAX_SPEED_DEFAULT * 2
values.BOAT_DECELERATION_DEFAULT = values.BOAT_ACCELERATION_DEFAULT / 4
values.BOAT_ROTATION_SPEED_DEFAULT = math.pi
values.BOAT_INTERACTION_RADIUS = 40
values.LANTERN_RADIUS = 125

values.FULL_GAS_AMOUNT = 100
values.DAY_TO_GAS_AMOUNT = {
	25,
	50,
	75,
	80,
	100,
}
values.GAS_DEPLETION_RATE_DEFAULT = 1.
values.GAS_ACCELERATION_DEPLETION_MULTIPLIER = 4.

-- packages
values.FUEL_CELL_INITIAL_GAS = 30
values.GLASS_BREAK_MIN_SPEED = 50

return values
