local Values = {}

-- boat
Values.BOAT_MAX_SPEED_DEFAULT = 50
Values.BOAT_MAX_BACKWARD_SPEED_DEFAULT = Values.BOAT_MAX_SPEED_DEFAULT / 2
Values.BOAT_ACCELERATION_DEFAULT = Values.BOAT_MAX_SPEED_DEFAULT * 2
Values.BOAT_DECELERATION_DEFAULT = Values.BOAT_ACCELERATION_DEFAULT / 4
Values.BOAT_ROTATION_SPEED_DEFAULT = math.pi
Values.BOAT_INTERACTION_RADIUS = 40
Values.LANTERN_RADIUS = 125

Values.FULL_GAS_AMOUNT = 100
Values.DAY_TO_GAS_AMOUNT = {
    30,
    60,
    75,
    80,
    100,
}
Values.GAS_DEPLETION_RATE_DEFAULT = 1.
Values.GAS_ACCELERATION_DEPLETION_MULTIPLIER = 4.

-- packages
Values.FUEL_CELL_INITIAL_GAS = 30
Values.GLASS_BREAK_MIN_SPEED = 50

return Values
