-- boat
BOAT_MAX_SPEED_DEFAULT = 75
BOAT_MAX_BACKWARD_SPEED_DEFAULT = BOAT_MAX_SPEED_DEFAULT / 2
BOAT_ACCELERATION_DEFAULT = BOAT_MAX_SPEED_DEFAULT * 2
BOAT_DECELERATION_DEFAULT = BOAT_ACCELERATION_DEFAULT / 4

INITIAL_GAS = 100
GAS_DEPLETION_RATE_DEFAULT = 1.

-- packages
FUEL_CELL_INITIAL_GAS = 30
